include: 
  - project: devops/ci
    file: /actions/index.yml

.all-branches:
  only:
    - master
    - develop

stages:
  - build
  - docker
  - deploy

build:
  extends: [.build, .all-branches]
  image: node:18.7.0-alpine
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir ~/.pnpm-store
  script:
    - NODE_ENV=development pnpm install --frozen-lockfile
    - npm run build
  artifacts:
    paths:
     - dist/
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

docker:
  extends: [.docker, .all-branches]

deploy_prod:
  extends: [.deploy-docker]
  tags: [deploy, worker]
  variables:
    DOCKER_SERVICE: prod_nest_workers
    VIRTUAL_HOST: Host(`nest.buzz.guru`)
    # DOCKER_STACK_DEBUG: 1
  environment:
    name: prod
    url: https://nest.buzz.guru
  only:
    - master
